README.md
The usage steps mentioned in the README do not work when installing and importing the library in a boilerplate app created using `create-react-app` command.
This PR fixes that by adding `@` symbol for scopes while adding the module.
=> docs: fix usage steps in README

packages/apsara-ui/src/FormBuilder/FormBuilder.stories.tsx, packages/apsara-ui/src/FormBuilder/index.tsx
Add an example to use `Form` components with `Tabs`. One thing to notice how it uses `form.getFieldsValue(true)` to get all the values of the form.
`Tabs` will not render content from inactive tabs. It means that form fields that reside in inactive tabs will not be available to form.
Calling `form.getFieldsValue()` will only give you fields that are being rendered which are those inside active tab only.
We need to pass `true` (`form.getFieldsValue(true)`) to make sure it returns all the values inside the form.
=> feat(Form): add example to use with Tabs

.prettierignore, components/accordion/index.tsx, components/alertdialog/index.tsx, components/avatar/index.tsx, components/bedge/index.tsx, components/contextmenu/index.tsx, components/dialog/index.tsx, components/dropdownmenu/index.tsx, components/menu/index.tsx, components/popover/index.tsx, components/radio/index.tsx, components/radiocard/index.tsx, components/sheet/index.tsx, components/table/filter/FilteredChip.tsx, components/table/filter/TableColumnFilterSelection.tsx, components/table/filter/TableColumnsViewFilter.tsx, components/table/index.tsx, components/table/inputs/select.tsx, components/tabs/index.tsx, index.ts
In React, compound components are a pattern for creating reusable components that have a parent component with multiple child components that work together to provide a specific functionality. The use of compound components provides flexibility to the developers in terms of customization, reusability, and maintainability of the codebase.
When it comes to creating compound components using menus in React, there are two approaches to create menu items: using `<MenuItem>` or `<Menu.Item>`
**Pros of using `<Menu.Item>`**
1. Clear naming: Using `<Menu.Item>` makes it clear that the component is a child of the <Menu> component.
2. Context awareness: Since `<Menu.Item>` is a child of `<Menu>`, it has access to the context of the parent component. This can be useful when creating more complex …
=> fix: support clear naming for Compound Components

apps/www/content/primitives/components/tabs.mdx
Currently, the code snippet representing the demo example was inaccurate as based on recent changes `<Tabs.List>` does not have a `pill` property. Updated `pill` to `elevated`.
=> doc: updated Tabs docs code snippet to reflect example Demo

packages/raystack/calendar/date-picker.tsx
**Issue:** On clicking outside the date-picker, the date-picker was reverting back to the previous date
**Cause:** handleMouseDown is wrapped under useCallback so that document.removeEventListener('mouseup', handleMouseDown) receives the same instance of handleMouseDown as document.addEventListener('mouseup', handleMouseDown). But due to this the calendarVal inside handleMouseDown -> removeEventListener was getting stale value
**Screenshot:**
https://github.com/user-attachments/assets/1a61d745-06be-4b0f-bf0d-c166a62c3454
=> fix: DatePicker outside click causing stale date updates

packages/raystack/calendar/date-picker.tsx
**Issue:**
- When user inputs incomplete date formats like 8/8/2024, the date is treated as invalid date
- Textfield by default is not selected on date-picker focus
**Screenshot for fix:**
https://github.com/user-attachments/assets/4229f132-c212-45e2-ac00-f0557ab05780
=> chore: Handle date conversion for wrong user inputs, and select text on textfield focus in date-picker

packages/raystack/table/datatable.tsx
Fallback to full screen loader if onLoadMore is not passed as props to the DataTable component.
=> fix: fallback to full screen loader if onLoadMore is undefined

apps/www/content/primitives/components/dialog.mdx, packages/raystack/dialog/dialog.module.css, packages/raystack/dialog/dialog.tsx
Added a prop, `overlayBlur` for the `DialogContent` component to show the blur effect on the Dialog overlay.
=> feat: blur effect on the overlay of dialog component

apps/www/content/primitives/components/calendar.mdx, packages/raystack/calendar/calendar.tsx
adds `loadingData` prop to show Skeleton in the month grid if we load data asynchronously.
adds an option to show tooltips for specific dates
=> feat: loading state and tooltip for specific dates in calendar component

apps/www/components/page.module.css, apps/www/components/primitive-page.tsx, apps/www/utils/routes.ts
Adds a "New" badge in the docs side bar if newBadge: true is passed in the route.
`{ title: "Button", slug: "docs/primitives/components/button", newBadge: true, },`
=> feat: add new badge on side nav

.npmignore, packages/raystack/package.json
Prevent node_modules and other folders/files from getting published to npm.
=> fix: prevert node_modules to publish to npm

apps/www/pages/_app.tsx, packages/raystack/v1/components/breadcrumb/breadcrumb.module.css, packages/raystack/v1/styles/accent.css
1. Match breadcrumb style.
2. Import v1 theme in _app instead of the older one.
3. Revert --rs-accent-contrast for mint accent color.
=> chore: match style for breadcrumb

packages/raystack/toggle-group/togglegroup.tsx, packages/raystack/v1/index.tsx
- Add missing import for tooltip provider
- Remove deprecation notice for toggleGroup old component as it is not yet present in v1.
Manual
=> fix: imports and remove unnecessary deprecate

packages/raystack/v1/components/tooltip/tooltip.tsx
Disabling asChild for tooltip as it's interfering with enclosing component.
Manually tested in example page.
Needs testing in end user project (Studio)
=> fix: tooltip asChild to false

packages/raystack/v1/styles/typography.css
Fix: revert default styling for html tags.
=> fix: remove overriding style for default html tags

packages/raystack/v1/components/dropdown-menu/dropdown-menu.module.css, packages/raystack/v1/components/select/select.module.css
Fix: Radix is overriding the outline css defined in `select.module.css` and making the outline transparent. Changing it to border.
Manual
=> fix: override prevent

packages/raystack/v1/components/tooltip/tooltip.tsx
Set default asChild to true for tooltip to prevent extra button html node.
If asChild is true, the trigger is rendered as the children passed to it. If it is false, it renders a new button node which in most cases is not needed.
Manual
=> fix: set default asChild as true

packages/raystack/v1/styles/typography.css
Note: This is not a sure shot fix and only makes the font closer to what is shown in Figma. I am currently researching on a tool called Capsize (or similar as it's deprecated) for this.
This PR addresses font rendering, but has some considerations:
**Font Smoothing Effects:**
- `-webkit-font-smoothing: antialiased` and `-moz-osx-font-smoothing: grayscale` make fonts appear thinner and smoother.
- These properties affect how the font is rendered (the crispness and weight) but don't address spacing issues.
`font-smooth: never` - Not using this.
- This is not a standard CSS property and has limited browser support
- It attempts to disable font smoothing entirely, which can make text appear more pixelated
Manual
=> fix: fix font difference

packages/raystack/v1/components/headline/headline.module.css, packages/raystack/v1/components/headline/headline.tsx, packages/raystack/v1/components/text/text.module.css, packages/raystack/v1/components/text/text.tsx
This PR adds the old styles back for backwards compatibility for the following components
- Text
- Headline
Manual
=> chore: Merge old styles for Text and Headline backwards compatibility

apps/www/src/app/examples/page.tsx, packages/raystack/v1/components/empty-state/empty-state.module.css
Fix: Add `text-wrap: wrap;` and `max-width: 360px;` to header and subHeader texts in EmptyState.
Manual
=> fix: add max-width to empty state

apps/www/src/content/docs/components/checkbox/index.mdx, apps/www/src/content/docs/components/command/index.mdx, packages/raystack/errorstate/errorstate.tsx, packages/raystack/textfield/textfield.tsx
- Deprecate old textField and ErrorState.
- Typo in doc
Manual
=> chore: deprecate old components

apps/www/src/app/examples/page.tsx, packages/raystack/v1/components/avatar/avatar.tsx, packages/raystack/v1/components/avatar/utils.test.ts, packages/raystack/v1/components/avatar/utils.tsx
The overflow Avatar picks the props of the first Avatar inside the AvatarGroup. If Avatar is enclosed inside another element like div, Flex, Tooltip, etc. overflow Avatar is no longer able to access Avatar props from the first level thus the styling of the overflow Avatar doesn't match other Avatars.
**Solution:**
Add a helper function which recursively checks if Avatar is enclosed inside other component and fetches the Avatar props and returns it. We match the props for overflow Avatar to the first Avatar.
Manual and unit test for thegetAvatarProps function
**Before:**
**After:**
=> Fix: Avatar overflow style mismatch

apps/www/src/app/examples/page.tsx, apps/www/src/content/docs/components/calendar/demo.ts, packages/raystack/v1/components/calendar/calendar.module.css
Fix: Prevent UI shift while changing month in date-picker and range-picker.
Docs: Update props for range-picker to appropriate context.
Manual
https://github.com/user-attachments/assets/fd31632d-5c44-491e-8a6e-7e755a8cede6
=> Fix (Calendar): Set fixed height to prevent UI shift

packages/raystack/v1/components/calendar/calendar.module.css
Fix: New select is causing the calendar popover height to increase.
Manual in range-picker and date-picker.
=> fix: accommodate calendar height change due to new select

apps/www/src/content/docs/components/grid/demo.ts, apps/www/src/content/docs/components/grid/index.mdx, apps/www/src/content/docs/components/grid/props.ts, packages/raystack/v1/components/grid/grid-item.tsx, packages/raystack/v1/components/grid/grid.tsx, packages/raystack/v1/components/grid/index.ts, packages/raystack/v1/components/grid/types.ts, packages/raystack/v1/index.tsx
This PR introduces a flexible Grid component
Manual
=> feat: grid component

.github/workflows/release-rc.yaml, .github/workflows/release.yaml
=> Fix release files tag main

packages/raystack/v1/components/calendar/date-picker.tsx, packages/raystack/v1/components/calendar/range-picker.tsx
=> fix: Error prop not overriding for date-picker

.github/workflows/release-rc.yaml, .github/workflows/release.yaml
This PR will add the [dist-tags](https://docs.npmjs.com/cli/v11/commands/npm-dist-tag#purpose) to the packages.
dist-tags can be added to packages with [--npm.tags](https://github.com/release-it/release-it/blob/main/docs/npm.md#tags) args.
using this tags, the user can install the package via alias.
eg. `npm i @raystack/frontier@latest` will install the latest stable version.
`npm i @raystack/frontier@next` will install the latest release candidate version.
=> ci: add npm dist tags to the package

packages/raystack/v1/components/breadcrumb/breadcrumb.tsx, packages/raystack/v1/components/data-table/components/filters.tsx
=> fix: dropdown in breadcrumb and table

apps/www/src/content/docs/components/breadcrumb/index.mdx, apps/www/src/content/docs/components/breadcrumb/props.ts, packages/raystack/v1/components/breadcrumb/breadcrumb.tsx
This PR adds `as` support for Breadcrumb items, allowing to render the item as custom elements
Manual
=> feat: breadcrumb `as` support

packages/raystack/v1/components/input-field/input-field.module.css
Currently set to inherit which makes the font-family a bit un predictable. Setting it to the font-family defined in the root.
Manual
=> fix (input-field): set font-family

packages/raystack/components/select/select-root.tsx
This PR fixes the bug where select was not working when placed inside form element
Manual
=> fix: select bug inside form

apps/www/src/app/examples/page.tsx, apps/www/src/content/docs/components/calendar/props.ts, packages/raystack/components/calendar/range-picker.tsx
This PR updates the RangePicker to support both controlled and uncontrolled mode.
**Note - `value` prop needs to be migrated to `defaultValue` for all RangePicker implementations as it will be fixed**
Manual
=> feat: support for controlled RangePicker

packages/raystack/components/breadcrumb/__tests__/breadcrumb.test.tsx, packages/raystack/components/breadcrumb/breadcrumb-item.tsx, packages/raystack/components/breadcrumb/breadcrumb-misc.tsx, packages/raystack/components/breadcrumb/breadcrumb.module.css
This PR updates the Breadcrumb component to improve design
Automated tests
=> feat: breadcrumb improvements

lefthook.yml, packages/raystack/figma.config.json, packages/raystack/figma/button.figma.tsx, packages/raystack/package.json, packages/raystack/scripts/update-figma-config.js, packages/raystack/scripts/validate-figma-config.js, pnpm-lock.yaml
This PR sets the base for figma code connect.
- Added button code connect
- Set up scripts for config handling (this is needed because figma.config doesn't support reading from env variables)
Manual
=> feat: figma code connect setup
