packages/apsara-ui/src/Listing/Filters/Filters.styles.tsx
packages/apsara-ui/src/Listing/Filters/index.tsx
packages/apsara-ui/src/Listing/InfiniteListing.tsx
packages/apsara-ui/src/Listing/Listing.stories.tsx

Introduce new prop on `InfiniteListing`
```jsx
<InfiniteListing
loading={false}
onApply={({ nextPage, search, filters }) => {
// handle filters e.g make api call
}}
/>
```

feat: add onApply to infinite listing

---

packages/apsara-ui/src/Codeblock/Codeblock.tsx
packages/apsara-ui/src/Notification/Notification.stories.tsx
packages/apsara-ui/src/Notification/Notification.tsx
packages/apsara-ui/src/Notification/index.tsx
packages/apsara-ui/src/index.ts

Revamp Notifications to allow with having a central root provider instead of referencing it on each usage.

feat(notifications): revamp contract

---

lerna.json
packages/apsara-icons/package.json
packages/apsara-ui/package.json

preparing deployment for 0.8.0

chore: bump version to 0.8.0

---

packages/raystack/sidebar/sidebar.module.css

fix: add sidebar background color
fix: remove overflow as it hides dropdown content

fix: add sidebar background color,

---

.changeset/wicked-fireants-flow.md
packages/raystack/table/datatable.tsx

https://tanstack.com/table/v8/docs/api/features/pagination#pagecount

fix: setting default page count to -1

---

.github/workflows/release.yml
apps/www/content/primitives/components/calendar.mdx
apps/www/pages/docs/primitives/components/[...slug].tsx
apps/www/types/frontmatter.d.ts
apps/www/utils/routes.ts
packages/raystack/.release-it.json
packages/raystack/calendar/calendar.module.css
packages/raystack/calendar/calendar.tsx
packages/raystack/calendar/index.tsx
packages/raystack/index.tsx
packages/raystack/package.json
packages/raystack/scripts/bump-version.js
pnpm-lock.yaml

This PR will add calendar component. 
Calendar component is just wrapper over [react-day-picker](https://react-day-picker.js.org/) with apsara styling.
This PR will also add support to auto bump package.json version with git tag instead of manually bumping version as pushing it.

feat: add calendar

---

examples/shield-ts/src/assets.tsx
packages/raystack/table/DataTableFilterChips.tsx
packages/raystack/table/FilteredChip.tsx
packages/raystack/table/TableContext.tsx
packages/raystack/table/datatable.module.css
packages/raystack/table/datatable.tsx
packages/raystack/table/datatables.types.tsx
packages/raystack/table/filterFns.tsx

filters preview https://apsara-git-featdatatablefilter-raystack.vercel.app/examples

feat: add filters to datatable

---

apps/www/components/Navbar/links.tsx
apps/www/content/primitives/components/errorstate.mdx
apps/www/utils/routes.ts
packages/raystack/errorstate/errorstate.tsx
pnpm-lock.yaml

close [106](https://github.com/raystack/apsara/issues/106)
preview https://apsara-git-featerrorstateaddmessage-raystack.vercel.app/docs/primitives/components/errorstate

feat: add message support to error state component

---

packages/raystack/table/DataTableFilterChips.tsx
packages/raystack/table/DataTableFilterOptions.tsx
packages/raystack/table/datatable.tsx

fix: show loading rows in data table and hide filter if disabled.

---

packages/raystack/dialog/dialog.tsx
packages/raystack/sheet/sheet.tsx

The content inside the dialog and sheet components is not scrollable.
ref to the fix https://github.com/radix-ui/primitives/pull/2250#issuecomment-2106048135

fix: scroll in dialog and sheet content

---

apps/www/examples/shield-ts/assets.tsx
apps/www/examples/shield-ts/data.tsx
apps/www/examples/shield-ts/dummy.ts
apps/www/examples/shield-ts/shield.tsx
apps/www/package.json
apps/www/pages/examples/index.tsx
packages/raystack/package.json
packages/raystack/table/datatable.tsx
pnpm-lock.yaml

IDE-555
1. Implement Infinite scroll in DataTable component. Table component accepts `onLoadMore` prop for infinite scroll.
2. Add bottom table loader.
3. Implement DataTable infinite scroll with dummy API in Example table.
4. Changed Example table layout.
5. Add Faker JS
6. Minor code refactor.
**Todo:**
1. Add support for filters.
2. Page number pagination.
**Testing:**
Tested on localhost with Example (www) project in Apsara.

feat (IDE-555): Add infinite scroll to table component

---

packages/raystack/package.json
packages/raystack/tooltip/tooltip.tsx
pnpm-lock.yaml

We should be able to pass class names for both `Trigger` of ToolTip and `Content` of ToolTip, for better customization.

feat: option to pass classes for trigger and content of ToolTip

---

packages/raystack/style.css

style: add new var space:

---

apps/www/content/primitives/components/button.mdx
apps/www/examples/shield-ts/assets.tsx
packages/raystack/button/button.module.css
packages/raystack/button/button.tsx
packages/raystack/style.css

OLD PR (closed) - [https://github.com/raystack/apsara/pull/146](https://github.com/raystack/apsara/pull/146)
**Desc**:
- Add new props to Button with added css.
- Parity with the design system.
- Add gap variable in global style.css.
- Updated mdx.
**Props**: (bold = default, all props optional)
1. variant = **primary**, secondary, outline, ghost, danger, text
2. size = **normal**, small
3. disabled = true, **false**
4. loading = true, **false**
5. className = string
6. onClick = fn()
7. loaderText = string
8. leadingIcon = ReactNode
9. trailingIcon = ReactNode
10. asChild = **false**, true
11. width = string, number
**Testing**:
Manually tested on Chrome

feat: Button component

---

apps/www/content/primitives/components/toast.mdx
apps/www/examples/shield-ts/assets.tsx
packages/raystack/toast/toast.tsx

Toast component for Apsara v2
Uses [Sonner](https://sonner.emilkowal.ski/getting-started) behind the scene.
| Prop | Description | Default |
|------|-------------|---------|
| description | Text shown below the title | - |
| duration | Auto-close time in milliseconds | `4000` |
| position | Toast position on screen | `bottom-right` |
| dismissible | Allow user to dismiss toast | `true` |
| Prop | Description | Default |
|------|-------------|---------|
| icon | Leading icon | - |
| invert | Inverts color scheme | `false` |
| closeButton | Show close button | `false` |
| unstyled | Remove default styling | `false` |
| Prop | Description | Default |
|------|-------------|---------|
| action | Primary button config | - |
| cancel | Secondary button config | - |
| actionButtonStyle | Primary …

feat: add toast component modifications

---

apps/www/components/datatable/datatable.tsx
apps/www/content/primitives/components/avatar.mdx
apps/www/pages/_app.tsx
packages/raystack/rollup.config.mjs
packages/raystack/v1/components/button/button.module.css
packages/raystack/v1/components/themprovider/theme.tsx
packages/raystack/v1/components/toast/toast.module.css
packages/raystack/v1/components/toast/toast.tsx

Changes
1. Avatar mdx - restore radix link
2. _apps revert the ~/styles import. Import the local styles from www folder.
3. Remove circular dependency warning from rollup config.
4. Toast remove style={{}} and use className.
5. Replace addListener to addEventListener in theme.

Multiple fixes and refactor

---

packages/raystack/table/FilteredChip.tsx

fix: typings fix

---

apps/www/components/hero/index.tsx
apps/www/examples/shield-ts/assets.tsx
packages/raystack/v1/components/breadcrumb/breadcrumb.module.css
packages/raystack/v1/components/button/button.module.css

chore: Update doc heading and CSS changes

---

packages/raystack/jest.config.ts
packages/raystack/jest.setup.ts
packages/raystack/package.json
packages/raystack/tsconfig.json
packages/raystack/v1/test-utils.tsx
pnpm-lock.yaml

Setup unit test. Jest and React-testing-library.

feat: setup jest and react-testing-library

---

packages/raystack/avatar/avatar.tsx
packages/raystack/badge/badge.tsx
packages/raystack/checkbox/checkbox.tsx
packages/raystack/dropdown-menu/dropdown-menu.tsx
packages/raystack/inputfield/inputfield.tsx
packages/raystack/text/text.tsx
packages/raystack/v1/components/badge/badge.tsx
packages/raystack/v1/index.tsx
packages/raystack/v1/styles/colors.css

Deprecated older components and old interfaces

chore: deprecate older components

---

packages/raystack/v1/styles/typography.css

feat: change cursor styling

---

packages/raystack/v1/components/spinner/__tests__/spinner.test.tsx
packages/raystack/v1/components/spinner/index.tsx

tests: add spinner test cases

---

apps/www/examples/shield-ts/assets.tsx
packages/raystack/v1/components/spinner/index.tsx
pnpm-lock.yaml

Incorrect comment close in assets file

fix: comment error

---

packages/raystack/v1/components/avatar/avatar.module.css

fix: avatar colors

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adds a pull request and issue template to the project
**Pull request template:**
**Issue template:**
[Provide a clear and concise description of the issue]
[Describe what you expected to happen]
[Describe what actually happened]
1. [First Step]
2. [Second Step]
3. [and so on...]
- OS: [e.g. Windows, MacOS]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
[Add any other context about the problem here]
[If applicable, add screenshots to help explain your problem]

feat: pull request and issue templates

---

packages/raystack/v1/components/calendar/calendar.tsx
packages/raystack/v1/components/calendar/date-picker.tsx
packages/raystack/v1/components/calendar/range-picker.tsx
packages/raystack/v1/components/callout/callout.tsx
packages/raystack/v1/components/input-field/input-field.tsx
packages/raystack/v1/components/popover/popover.tsx
packages/raystack/v1/components/search/search.tsx
packages/raystack/v1/components/select/select.tsx
packages/raystack/v1/components/sidepanel/sidepanel.tsx
packages/raystack/v1/components/slider/slider.tsx
packages/raystack/v1/components/text-area/text-area.tsx
packages/raystack/v1/components/textfield/textfield.tsx
packages/raystack/v1/components/tooltip/tooltip.tsx
packages/raystack/v1/index.tsx

refactor: sort imports

---

apps/www/content/primitives/components/button.mdx
packages/raystack/v1/components/calendar/calendar.module.css

- Calendar dropdown spacing and padding fix.
- Button was looking weird due to formatting in button.mdx.
Manually

fix: calendar css and button docs

---

packages/raystack/v1/components/calendar/calendar.module.css
packages/raystack/v1/components/calendar/date-picker.tsx

Fix (Date picker): Left align text for the default trigger
Manual

fix(calendar): default trigger text alignment

---

packages/raystack/v1/styles/colors.css
packages/raystack/v1/styles/primitives/accent.css
packages/raystack/v1/styles/primitives/appearance.css
packages/raystack/v1/styles/primitives/gray.css

refactor: restructure more css

---

packages/raystack/v1/components/button/button.module.css
packages/raystack/v1/styles/typography.css

feat: typography add vars

---

packages/raystack/v1/components/text/text.module.css

Fix: Incorrect text component behaviour
Tested on examples page but needs confirmation from Studio team as well.

fix: incorrect text display behaviour

---

packages/raystack/v1/components/avatar/avatar.module.css
packages/raystack/v1/components/badge/badge.module.css
packages/raystack/v1/components/breadcrumb/breadcrumb.module.css
packages/raystack/v1/components/button/button.module.css
packages/raystack/v1/components/calendar/calendar.module.css
packages/raystack/v1/components/callout/callout.module.css
packages/raystack/v1/components/chip/chip.module.css
packages/raystack/v1/components/dropdown-menu/dropdown-menu.module.css
packages/raystack/v1/components/text/text.module.css

Update the new Typography css variable changes to v1 components.
Affects below components:
- avatar
- badge
- breadcrumb
- button
- calendar
- callout
- chip
- dropdown-menu
- text
Manual

refactor: add typography variables to v1 components

---

apps/www/examples/shield-ts/assets.tsx

fix: imports

---

apps/www/content/primitives/components/select.mdx
apps/www/utils/routes.ts
packages/raystack/select/select.tsx
packages/raystack/v1/components/select/select.module.css
packages/raystack/v1/components/select/select.tsx
packages/raystack/v1/index.tsx

feat: add select v1

---

apps/www/content/primitives/components/chip.mdx
packages/raystack/v1/components/chip/chip.module.css
packages/raystack/v1/components/chip/chip.tsx

fix: change chip prop from style to color as it's reserved keyword
fix: disable user text select

fix: change chip prop from style to color as it's reserved keyword

---

packages/raystack/v1/components/icon-button/icon-button.tsx
packages/raystack/v1/components/tooltip/tooltip.tsx

feat: add className and style properties for iconButton and tooltip
Additions in Tooltip:
- style?: React.CSSProperties
Additions in IconButton:
- classNames?:object; 
- style?: React.CSSProperties; 
Manual

feat: add className and style to tooltip and iconButton

---

packages/raystack/v1/components/empty-state/empty-state.module.css

Add top margin to compensate for height of absolute div.
manual

fix: add top margin

---

apps/www/content/primitives/components/select.mdx
package.json
packages/raystack/v1/components/badge/badge.module.css
packages/raystack/v1/components/input-field/input-field.module.css
pnpm-lock.yaml

Fix: Update scope in select docs
Feat: add start script which runs package and example.
Fix: add height to badge.
Fix: Remove min-width to input field
Manual

fix: add scope for select component docs and add package script

---

apps/www/pages/examples/data-table.tsx
packages/raystack/v1/components/data-table/components/display-settings.tsx
packages/raystack/v1/components/data-table/components/grouping.tsx
packages/raystack/v1/components/data-table/data-table.types.tsx
packages/raystack/v1/components/data-table/utils/index.tsx
packages/raystack/v1/components/table/table.module.css

fix: minor issues in datatable 

---

packages/raystack/v1/components/data-table/components/search.tsx

fix(datatable): add onClear and value to search component

---

apps/www/content/primitives/components/sidebar.mdx
apps/www/examples/shield-ts/shield.tsx
packages/raystack/v1/components/sidebar/sidebar.module.css
packages/raystack/v1/components/sidebar/sidebar.tsx

- Chore: Change `<Sidebar.Root>` to `<Sidebar>`
- Fix: Center icon horizontally in collapsed state.
- Fix: Add bottom padding in sidebar root
- Refactor: Use semantic tags aside and nav

chore: Sidebar fixes

---

packages/raystack/v1/components/tooltip/tooltip.tsx

Tooltip doesn't work on Text component without a div.
Needs testing on Studio

fix: tooltip behaviour

---

packages/raystack/v1/components/data-table/components/content.tsx
packages/raystack/v1/components/data-table/components/display-properties.tsx

fix: show loader only for visible columns

---

apps/www/components/datatable/datatable.tsx
apps/www/content/primitives/components/datatable.mdx
apps/www/pages/examples/data-table.tsx
packages/raystack/v1/components/data-table/components/content.tsx
packages/raystack/v1/components/data-table/components/display-settings.tsx
packages/raystack/v1/components/data-table/components/filters.tsx
packages/raystack/v1/components/data-table/components/grouping.tsx
packages/raystack/v1/components/data-table/components/ordering.tsx
packages/raystack/v1/components/data-table/data-table.module.css
packages/raystack/v1/components/data-table/data-table.tsx
packages/raystack/v1/components/data-table/data-table.types.tsx
packages/raystack/v1/components/data-table/hooks/useFilters.tsx
packages/raystack/v1/components/data-table/index.ts
packages/raystack/v1/components/data-table/utils/filter-operations.tsx
packages/raystack/v1/components/data-table/utils/index.tsx
packages/raystack/v1/components/filter-chip/filter-chip.tsx
packages/raystack/v1/components/table/table.tsx
packages/raystack/v1/index.tsx
packages/raystack/v1/types/filters.tsx

This PR will make the following changes.
1. Add a onRowClick to the Datatable with hover state to the row.
2. Add string, number, and bool values in the RQL Filter.
3. Add support for an empty string in the select filter.
4. Rename columnType to filterType and make it optional.
5. Add dataType to column definition which will be used in `select` filterType

feat:  add onRowClick and fix RQL filter values

---

apps/www/examples/shield-ts/assets.tsx
packages/raystack/v1/components/tooltip/tooltip.tsx

Feat (Tooltip): Add `showArrow` prop to tooltip.
Manual

feat: add showArrow prop

---

apps/www/examples/shield-ts/assets.tsx
packages/raystack/v1/components/spinner/spinner.module.css

Reverse spinner rotation direction
Manual

fix: spinner direction change

---

apps/www/examples/shield-ts/assets.tsx
packages/raystack/v1/components/text-area/text-area.module.css
packages/raystack/v1/components/text-area/text-area.tsx

Feat: add info `Tooltip` to `Text Area`
Fix: change label weight to normal.
Manual

feat: add info tooltip

---

packages/raystack/v1/components/data-table/components/content.tsx
packages/raystack/v1/components/data-table/data-table.types.tsx

feat: add wrapper to datatable content

---

apps/www/components/page.module.css
apps/www/components/primitive-page.tsx
apps/www/content/primitives/components/side-panel.mdx
apps/www/utils/routes.ts
packages/raystack/v1/components/side-panel/index.tsx
packages/raystack/v1/components/side-panel/side-panel.module.css
packages/raystack/v1/components/side-panel/side-panel.tsx
packages/raystack/v1/index.tsx

Sidepanel v1 component.
Manual

Feat: Add Sidepanel component

---

apps/www/src/app/assets/page.tsx

Adds a dev page at `/assets` url for internal use.
Manual

chore: add dev page in apsara

---

apps/www/src/content/docs/components/dialog/demo.ts
apps/www/src/content/docs/components/dialog/index.mdx
apps/www/src/content/docs/components/dialog/props.ts
packages/raystack/v1/components/dialog/dialog.module.css
packages/raystack/v1/components/dialog/dialog.tsx

Feat dialog design

---

apps/www/src/content/docs/components/dialog/demo.ts
apps/www/src/content/docs/components/dialog/index.mdx
apps/www/src/content/docs/components/dialog/props.ts
packages/raystack/v1/components/dialog/dialog.tsx

fix: seperate dialog close and close button

---

packages/raystack/v1/components/data-table/components/search.tsx
packages/raystack/v1/components/input-field/input-field.tsx
packages/raystack/v1/components/search/search.tsx

fix: forwardRef in InputField and Search component

---

apps/www/package.json
apps/www/source.config.ts
apps/www/src/app/docs/[[...slug]]/page.module.css
apps/www/src/app/docs/[[...slug]]/page.tsx
apps/www/src/app/docs/layout.tsx
apps/www/src/components/demo/demo.tsx
apps/www/src/components/docs/sidebar-item.module.css
apps/www/src/components/docs/sidebar-item.tsx
apps/www/src/components/editor/editor.tsx
apps/www/src/components/preview/preview.tsx
apps/www/src/components/tag/index.ts
apps/www/src/components/tag/tag.module.css
apps/www/src/components/tag/tag.tsx
apps/www/src/content/docs/components/copy-button/demo.ts
apps/www/src/content/docs/components/copy-button/index.mdx
apps/www/src/content/docs/components/copy-button/props.ts
apps/www/src/content/docs/components/icon-button/demo.ts
apps/www/src/content/docs/components/radio/demo.ts
apps/www/src/content/docs/components/sidepanel/demo.ts
apps/www/src/content/docs/components/sidepanel/index.mdx
apps/www/src/content/docs/components/sidepanel/props.ts
apps/www/src/lib/prettier.ts
apps/www/src/lib/types.ts
apps/www/src/lib/utils.ts
pnpm-lock.yaml

- Beautify code snippets in preview and playground
- Update missing docs (some docs which were recently added needs to be migrated)
- CopyButton
- SidePanel
- Add support for tags - NEW, BETA
Manual

feat: docs improvements

---

apps/www/src/app/icons/layout.tsx
apps/www/src/app/icons/page.module.css
apps/www/src/app/icons/page.tsx
apps/www/src/app/icons/styles.module.css
apps/www/src/components/icon-details/icon-details.module.css
apps/www/src/components/icon-details/icon-details.tsx
apps/www/src/components/icon-details/icon-empty.tsx
apps/www/src/components/icon-details/index.ts
apps/www/src/components/navbar/navbar.tsx

A page to search and view all icons is needed in the documentation
- View all available icons
- Search through the icons
- Copy import/icon name
Manual

feat: add icons page

---

apps/www/src/app/examples/page.tsx
packages/raystack/v1/components/calendar/calendar.module.css
packages/raystack/v1/components/calendar/range-picker.tsx

- Feat: Add footer to range-picker component
- Fix: Fix default input trigger outline color
Manual

feat: add footer to range-picker

---

packages/raystack/v1/components/data-table/data-table.tsx

fix: datatable search update

---

apps/www/src/content/docs/components/headline/demo.ts
apps/www/src/content/docs/components/headline/props.ts
packages/raystack/v1/components/headline/headline.module.css
packages/raystack/v1/components/headline/headline.tsx
packages/raystack/v1/components/headline/index.tsx

- Updates Headline component to fix typography changes
Manual

feat: headline update and docs

---

apps/www/src/components/navbar/navbar.tsx
apps/www/src/content/docs/components/link/demo.ts
apps/www/src/content/docs/components/link/index.mdx
apps/www/src/content/docs/components/link/props.ts
apps/www/src/content/docs/components/text/demo.ts
apps/www/src/content/docs/components/text/index.mdx
apps/www/src/content/docs/components/text/props.ts
packages/raystack/tsconfig.json
packages/raystack/v1/components/link/link.module.css
packages/raystack/v1/components/link/link.tsx
packages/raystack/v1/components/text/index.tsx
packages/raystack/v1/components/text/text.module.css
packages/raystack/v1/components/text/text.tsx
packages/raystack/v1/index.tsx

- Introduces new props to Text component
- lineClamp
- underline
- italic
- transform
- align
- as
- Update Text component as per updated typography 
- Fix proper ref forwarding for Text
- Refactor Link component to remove redundant code and build on top of Text
Manual

feat: Text and Link Improvements

---

packages/raystack/v1/styles/index.css
packages/raystack/v1/styles/reset.css

feat: Added button css reset

---

.github/workflows/release.yml

chore: Removed main branch dependency from release.yml to allow patch release for tag

---

packages/raystack/.release-it.json

chore: Updated release-it.json for quick tag release

---

.github/workflows/release.yml

Revert "chore: Removed main branch dependency from release.yml to allow patch release for tag"

---

packages/raystack/.release-it.json

Revert "chore: Updated release-it.json for quick tag release"

---

packages/raystack/v1/components/calendar/range-picker.tsx

chore: Separated textfield props for start and end date in range picker

---

apps/www/src/app/examples/page.tsx
apps/www/src/content/docs/components/dropdown/demo.ts
packages/raystack/package.json
packages/raystack/v1/components/dropdown-menu/cell.module.css
packages/raystack/v1/components/dropdown-menu/cell.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu-content.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu-item.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu-misc.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu-root.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu-trigger.tsx
packages/raystack/v1/components/dropdown-menu/dropdown-menu.module.css
packages/raystack/v1/components/dropdown-menu/dropdown-menu.tsx
packages/raystack/v1/components/dropdown-menu/utils.ts
packages/raystack/v1/icons/assets/triangle-right.svg
packages/raystack/v1/icons/index.tsx
pnpm-lock.yaml

This PR updates the dropdown component
- Support for searchable menu via `autocomplete` prop
- Internally uses Combobox from AriaKit
- Support for select items (`menuitemradio`)
- Support for nested menus
Manual

feat: dropdown 2.0

---

packages/raystack/v1/components/button/button.module.css

Fix: Color changing on hover in loading state for outline button variant.
Manual

fix: button loading hover

---

packages/raystack/v1/components/input-field/input-field.tsx

- Handle ref forwarding correctly.
- Explicit ref prop is not needed as forwardRef handles it.

fix: handle ref forwarding correctly

---

apps/www/src/app/examples/page.tsx
packages/raystack/v1/components/button/button.tsx
packages/raystack/v1/components/spinner/spinner.module.css
packages/raystack/v1/components/spinner/spinner.tsx

Feat: add new colors to spinner
Manual

feat: add new colors support to spinner and render correctly in button

---

apps/www/src/content/docs/components/spinner/demo.ts
apps/www/src/content/docs/components/spinner/index.mdx
apps/www/src/content/docs/components/spinner/props.ts
packages/raystack/v1/components/spinner/__tests__/spinner.test.tsx

Update docs and test cases
Manual

docs: update props for Spinner

---

apps/www/src/app/examples/page.tsx
packages/raystack/v1/components/avatar/avatar.module.css
packages/raystack/v1/components/dialog/dialog.module.css
packages/raystack/v1/components/dropdown-menu/dropdown-menu.module.css
packages/raystack/v1/components/indicator/indicator.module.css
packages/raystack/v1/components/input-field/input-field.module.css
packages/raystack/v1/components/popover/popover.module.css
packages/raystack/v1/components/search/search.module.css
packages/raystack/v1/components/select/select.module.css
packages/raystack/v1/components/sheet/sheet.module.css
packages/raystack/v1/components/tooltip/tooltip.module.css
packages/raystack/v1/styles/index.css
packages/raystack/v1/styles/primitives/z-index.css

Add `--rs-z-index-portal:99` for all portals.
Manual on Apsara and Studio.

feat: z-index vars

---

apps/www/src/app/examples/page.tsx
packages/raystack/v1/components/calendar/calendar.module.css
packages/raystack/v1/components/calendar/range-picker.tsx

Fix: Incorrect date range selection when clicked in selected range.
Style: Today dot color
Manual

Fix (Calendar): incorrect date selection when clicked on selected range

---

packages/raystack/v1/components/filter-chip/filter-chip.module.css
packages/raystack/v1/components/filter-chip/filter-chip.tsx

Fixes FilterChip select css 
Manual

feat: fix filter chip select css

---

packages/raystack/v1/components/calendar/range-picker.tsx

https://github.com/user-attachments/assets/6a8021db-4808-439d-a2ea-265481eee447

chore: Range picker reset when invalid date range

---

apps/www/src/app/examples/page.tsx
apps/www/src/content/docs/components/calendar/demo.ts
packages/raystack/v1/components/calendar/calendar.module.css
packages/raystack/v1/components/calendar/calendar.tsx

Fix: Select alignment on calendar

Style (Calendar): Select and nav button alignment

---

apps/www/src/content/docs/getting-started.mdx
packages/raystack/index.tsx
packages/raystack/normalize.css
packages/raystack/package.json
packages/raystack/rollup.config.mjs

This adds a normalize.css file to apsara, and exports it. This is optional and user can opt-in to use the stylesheet if needed.
Manual

feat: expose normalize.css from apsara

---

apps/www/src/app/examples/page.tsx
packages/raystack/v1/components/calendar/range-picker.tsx

fix: range-picker shows only one month when last month is selected

fix: range-picker shows only one month when last month is selected

---

packages/raystack/v1/components/select/select.module.css

fix(select): adjust overflow behavior to allow y axis scroll
Manual

fix(select): adjust overflow behavior to allow y axis scroll

---

.github/workflows/release.yaml

fix: ci breaking as checkout position is incorrect
Can be tested after merge

fix: ci breaking as checkout position incorrect

---

.github/workflows/release.yaml

Fix: workflow failing as git is not initialised
Can be tested after the merge

fix (CI): Workflow breaking

---

.github/workflows/release.yaml
packages/raystack/package.json

fix: update version in package.json

---

.github/workflows/release.yaml

fix: ci breaking as checkout position incorrect (#391)

---

.github/workflows/release-rc.yaml

ci: create release file for rc tags

---

.github/workflows/release-rc.yaml
.github/workflows/release.yaml

fix: update tag regex in github action

---

apps/www/src/app/examples/page.tsx
apps/www/src/content/docs/components/select/demo.ts
apps/www/src/content/docs/components/select/index.mdx
apps/www/src/content/docs/components/select/props.ts
packages/raystack/v1/components/select/select-content.tsx
packages/raystack/v1/components/select/select-item.tsx
packages/raystack/v1/components/select/select-root.tsx
packages/raystack/v1/components/select/select-trigger.tsx
packages/raystack/v1/components/select/select.module.css

This PR adds `autocomplete` support for Select. Uses Ariakit Combobox to enable the functionality. Autocomplete can be used both in auto or manual mode
Manual

feat: add `autocomplete` support for Select

---

apps/www/src/content/docs/components/tooltip/props.ts
packages/raystack/v1/components/tooltip/tooltip.module.css
packages/raystack/v1/components/tooltip/tooltip.tsx

This PR fixes the Tooltip.Arrow style
Manual

fix: Tooltip.Arrow style 

---

packages/raystack/v1/components/sidebar/sidebar.module.css
packages/raystack/v1/components/sidebar/sidebar.tsx

chore: Make icon optional for SIdebar.Item
fix: Item bg overflowing to left

fix (Sidebar): Item and container css fixes

---

apps/www/src/content/docs/components/tooltip/demo.ts
apps/www/src/content/docs/components/tooltip/index.mdx
apps/www/src/content/docs/components/tooltip/props.ts
packages/raystack/v1/components/sidebar/sidebar.tsx
packages/raystack/v1/components/tooltip/tooltip.module.css
packages/raystack/v1/components/tooltip/tooltip.tsx
packages/raystack/v1/components/tooltip/utils.ts
packages/raystack/v1/hooks/index.tsx
packages/raystack/v1/hooks/useMouse.tsx

This PR adds support for tooltip `followCursor`
Manual

feat: tooltip `followCursor` mode

---

apps/www/src/app/examples/page.tsx
apps/www/src/content/docs/components/tooltip/demo.ts
apps/www/src/content/docs/components/tooltip/index.mdx
apps/www/src/content/docs/components/tooltip/props.ts
packages/raystack/v1/components/icon-button/icon-button.module.css
packages/raystack/v1/components/icon-button/icon-button.tsx
packages/raystack/v1/components/sidebar/sidebar.module.css
packages/raystack/v1/components/sidebar/sidebar.tsx
packages/raystack/v1/components/table/table.module.css
packages/raystack/v1/components/tooltip/tooltip.module.css
packages/raystack/v1/components/tooltip/tooltip.tsx
packages/raystack/v1/components/tooltip/utils.ts
packages/raystack/v1/hooks/index.tsx
packages/raystack/v1/hooks/useMouse.tsx

chore: sync main into develop

---

.github/workflows/sync-develop.yaml

Auto trigger main -> develop sync PR when pushed to main.
**Note**: main and develop branch should be protected. sync PRs must be merged using `Create a merge commit` option
Tested on separate dummy repo. Needs testing after merge in this project.
Scenarios tested on the dummy project:
- `hotfix` raised from `main` and merged to `main` -> Should raise a sync PR with source branch from `main` and target branch to `develop`.
- 'feat' / 'fix' raised from `develop` and merged to `develop` -> No sync PR should be raised
- Release PR created from `develop` into `main` and merged -> No sync PR should be raised

ci: add sync develop main flow

---

apps/www/src/content/docs/index.mdx

docs: copy fix

---

packages/raystack/v1/components/data-table/components/content.tsx
packages/raystack/v1/components/flex/flex.module.css
packages/raystack/v1/components/flex/flex.tsx

fix: table loader skeleton

---

packages/plugin-vscode/package.json
packages/raystack/package.json
pnpm-lock.yaml

- Remove unused dependencies from apsara package
- Add metadata for VSC Plugin
Manual

chore: update package.json

---

packages/raystack/package.json
packages/raystack/scripts/bump-version.js

fix: bump scripts

---

packages/raystack/components/dropdown-menu/dropdown-menu-misc.tsx

This PR fixes the dropdown separator color
Manual

fix: dropdown separator

---

packages/raystack/components/avatar/avatar.module.css
packages/raystack/components/avatar/avatar.tsx

This PR fixes the avatar to properly pass props
Manual

fix: avatar props 

---

apps/www/src/app/examples/page.tsx
apps/www/src/content/docs/components/amount/demo.ts
apps/www/src/content/docs/components/amount/index.mdx
apps/www/src/content/docs/components/amount/props.ts
packages/raystack/components/amount/amount.tsx

- Add try..catch.
- Add string type for value.
- ts-ignore string value errors.
- Add console warning if the number is greater than JS's safe int limit.
- Handle string and number manipulation separately as we cannot convert big numbers to string as it will loose precision.
Updated docs.

fix (Amount): handle big integer in value prop

---

apps/www/tsconfig.json
packages/raystack/package.json
packages/raystack/rollup.config.mjs
pnpm-lock.yaml

- Updates Apsara to use React 19
- Adds peerDeps to support both React 18 & React 19
Manual

feat: support react 19

---

apps/www/src/components/playground/switch-examples.tsx
apps/www/src/content/docs/components/switch/demo.ts
apps/www/src/content/docs/components/switch/index.mdx
apps/www/src/content/docs/components/switch/props.ts
packages/raystack/components/switch/switch.module.css
packages/raystack/components/switch/switch.tsx

This PR introduces a new size variant for the switch component
Manual

feat: add size variant for switch
